### ISSUE TITLE
Invalid value encountered in sqrt

### ISSUE THREAD

**Issue by denkorz** [RomainPastureau/find_delay#4]
When I call this:
delay = find_delay(audio1, audio2,
           compute_envelope=True, window_size_env=1e6, overlap_ratio_env=0.5,
           resampling_rate=1000, window_size_res=1e7, overlap_ratio_res=0.5, return_delay_format="timedelta",
           resampling_mode="cubic", plot_figure=False, path_figure=plot, plot_intermediate_steps=True,
           verbosity=1)

Sometimes it happens that I face this issue:
find_delay/find_delay.py:1430: RuntimeWarning: invalid value encountered in sqrt
  cross_correlation = correlate(y1, y2_normalized, "full") / np.sqrt(y1_m2 - y1_m)
  
  Usually it happens when reference file (left on plot) is shorter than actual. But now it happens too often with these 2 files.
  I believe it might happen due to absolute zero in volume of reference file at the beggining and the end that breakes squares by making them negative for some reason.
  But the interesting fact is the plot file generates and indicates that everything is perfect.
  
  Here is a link to a zip folder with 2 files leading to the error and the plot I got.
https://drive.google.com/file/d/1GzPuf-sGpYVUhCtoVlYj8XKG0iJ0l27G/view?usp=sharing

**Comment by RomainPastureau** [comment]
Hi!

Thank you for using this package.

The RuntimeWarning that you have been seeing happens because there seem to be a rounding error with a very small value (< 10e13) during the cross-correlation. For this one value, numpy calculates a negative square root, which creates a nan value and raises a Runtime Warning.

I have seen it behaving like this in the past with data of my own, but never really thought of investigating it. In order to remove this warning, I'm currently updating the code to set any negative value to zero. Note that this provoked a new warning (division by 0), that I prevented by setting any division by 0 equal to 0 (which we want for the cross-correlation calculation).

I will perform some testing to ensure this doesn't break anything, along with adding a few new features. I will close the issue when the new version is live!

**Comment by RomainPastureau** [comment]
Version 2.12 is now live and should remove the warning. Please let me know if you see any weird behaviour in the package with the most recent changes.

This version also comes with a few improvements, all of which you can see on the [version history](https://find-delay.readthedocs.io/en/latest/version_history.html) page.
